### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by cl66666** [sahandk/HINTRA#1]
Hi,
In ubuntu 18.04, I used clang++ to compile the program. I created the input files based on the example and ran the program, and then I got 'Segmentation fault (core dumped)'.

**Comment by sahandk** [comment]
Hi,

Please make sure that the files are tab separated and the input arguments are provided correctly. If you still continue to get the error message, please share your input files.

**Comment by cl66666** [comment]
The command for using Hintra is as follows: ./Hintra-Lin -u ../example1/ 5 4 0.1 50 4
The input files and error message is as follows:
[example1.zip](https://github.com/sahandk/HINTRA/files/3450139/example1.zip)
s:

**Comment by sahandk** [comment]
The problem is that the name of the input file is not provided correctly. Assuming that the _example.Rcounts_ and other input files are in the folder _../example1_, the command should be

**./Hintra-Lin -u ../example1/example 5 4 0.1 50 4**

The name used for the input files with extentions _.Rcounts_, _.Vcounts_, etc., which is _example_ in this case, should be identified in the argument. The _path\_to\_input_ argument does not only specify the folder but also includes the file name.

**Comment by sahandk** [comment]
The usage guidelines are updated for more clarity.

**Comment by cl66666** [comment]
The problem has been solved, thanks a lot!
